name: Frontend e2e test

on:
  push:

jobs:
  e2e_test:
    name: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout alpha code
        uses: actions/checkout@v3

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Start e2e testing
        run: npx playwright test ./e2e

      - name: Dump docker logs on failure using different shell
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          shell: '/bin/sh'

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: tracer(Chrome)
          path: ./frontend/test-results/
          retention-days: 30
