name: Frontend e2e test

on:
  workflow_call:

jobs:
  has_file_changed:
    name: Has file changed
    runs-on: ubuntu-latest
    steps:
      - name: Download commit tags from artifact
        uses: actions/download-artifact@v3
        with:
          name: docker_pushed_tags_current_commit

      - name: Download flags file from artifact
        uses: actions/download-artifact@v3
        with:
          name: ci_flag

      - name: Is skip e2e test
        run: |
          cat flags.txt
          run=$(grep -e "INTEGRATION_START=" docker_image_tags.txt | sed "s/INTEGRATION_START=//g")
          frontend_changed=$(grep -e "E2E_START=" flags.txt | sed "s/E2E_START=//g")
          echo docker_image_tags.txt
          echo $run
          if [ -n "$run" ] || [ -n "$frontend_changed" ];then echo "changed=true" >> $GITHUB_ENV; else echo "changed=false" >> $GITHUB_ENV; fi
          echo ${{ env.changed }}
    outputs:
      file_changed: ${{ env.changed }}

  e2e_test:
    runs-on: ubuntu-8cpu-16ram
    needs: has_file_changed
    if: needs.has_file_changed.outputs.file_changed == 'true'
    defaults:
      run:
        working-directory: /home/runner/work/alpha/alpha
    steps:
      - name: Checkout alpha code
        uses: actions/checkout@v3

      - name: Cache playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: |
            ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Start e2e testing
        run: npx playwright test ./e2e

      - name: Dump docker logs on failure using different shell
        if: failure()
        uses: jwalton/gh-docker-logs@v1
        with:
          shell: '/bin/sh'

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: tracer(Chrome)
          path: ./frontend/test-results/
          retention-days: 30
